services:
  pgbouncer:
    image: edoburu/pgbouncer:latest
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt

networks:
  default:
