services:
  cloudql:
    image:  gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
    networks:
      - default
    environment:
      # configure proxy with environment variables
      # ICN should be the instance connection name
      - CSQL_PROXY_INSTANCE_CONNECTION_NAME=${ICN}
      - CSQL_PROXY_ADDRESS=0.0.0.0
      - CSQL_PROXY_PORT=5432
      - CSQL_PROXY_TOKEN=${TOKEN}

  pgbouncer:
    image: edoburu/pgbouncer:latest
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt

networks:
  default:
